"""empty message

Revision ID: 721599a46071
Revises: 9bd94c21be45
Create Date: 2026-03-06 16:33:39.911547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '721599a46071'
down_revision: Union[str, Sequence[str], None] = '9bd94c21be45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_acao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classe_acao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade_acoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natureza_operacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capital_realizado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_a_pagar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('averbacoes_onus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assinatura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookentry')
    # ### end Alembic commands ###
