"""add empresa transferencia

Revision ID: e19fd9e6f696
Revises: 35b15ba18708
Create Date: 2026-04-18 14:43:06.450022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e19fd9e6f696'
down_revision: Union[str, Sequence[str], None] = '35b15ba18708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferenciaentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sede', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cedente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade_acoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cessionario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_assinatura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('livro_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diretor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'registro'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('book_type')

    op.drop_table('transferenciaentry')
    # ### end Alembic commands ###
